
  ## Create Category to CategoryGroup Mapping
Categories<-rbind(
                  c("U.S. Equity", "Large Value"),
                  c("U.S. Equity", "Large Blend"),
                  c("U.S. Equity", "Large Growth"),
                  c("U.S. Equity", "Mid-Cap Value"),
                  c("U.S. Equity", "Mid-Cap Blend"),
                  c("U.S. Equity", "Mid-Cap Growth"),
                  c("U.S. Equity", "Small Value"),
                  c("U.S. Equity", "Small Blend"),
                  c("U.S. Equity", "Small Growth"),
                  c("U.S. Equity", "Leveraged Net Long"),
                  c("Sector Equity", "Communications"),
                  c("Sector Equity", "Consumer Cyclical"),
                  c("Sector Equity", "Consumer Defensive"),
                  c("Sector Equity", "Energy Limited Partnership"),
                  c("Sector Equity", "Equity Energy"),
                  c("Sector Equity", "Equity Precious Metals"),
                  c("Sector Equity", "Financial"),
                  c("Sector Equity", "Global Real Estate"),
                  c("Sector Equity", "Health"),
                  c("Sector Equity", "Industrials"),
                  c("Sector Equity", "Infrastructure"),
                  c("Sector Equity", "Natural Resources"),
                  c("Sector Equity", "Real Estate"),
                  c("Sector Equity", "Technology"),
                  c("Sector Equity", "Utilities"),
                  c("Sector Equity", "Miscellaneous Sector"),
                  c("Allocation", "Allocation--15% to 30% Equity"),
                  c("Allocation", "Allocation--30% to 50% Equity"),
                  c("Allocation", "Allocation--50% to 70% Equity"),
                  c("Allocation", "Allocation--70% to 85% Equity"),
                  c("Allocation", "Allocation--85%+ Equity"),
                  c("Allocation", "Convertibles"),
                  c("Allocation", "World Allocation"),
                  c("Allocation", "Tactical Allocation"),
                  c("Allocation", "Target-Date 2000-2010"),
                  c("Allocation", "Target-Date 2015"),
                  c("Allocation", "Target-Date 2020"),
                  c("Allocation", "Target-Date 2025"),
                  c("Allocation", "Target-Date 2030"),
                  c("Allocation", "Target-Date 2035"),
                  c("Allocation", "Target-Date 2040"),
                  c("Allocation", "Target-Date 2045"),
                  c("Allocation", "Target-Date 2050"),
                  c("Allocation", "Target-Date 2055"),
                  c("Allocation", "Target-Date 2060+"),
                  c("Allocation", "Target-Date Retirement"),
                  c("International Equity", "Foreign Large-Value"),
                  c("International Equity", "Foreign Large-Blend"),
                  c("International Equity", "Foreign Large-Growth"), 
                  c("International Equity", "Foreign Small/Mid-Value"),
                  c("International Equity", "Foreign Small/Mid-Blend"),
                  c("International Equity", "Foreign Small/Mid-Growth"),
                  c("International Equity", "World Stock"),
                  c("International Equity", "Diversified Emerging Markets"),
                  c("International Equity", "Diversified Pacific/Asia"),
                  c("International Equity", "Miscellaneous Region"),
                  c("International Equity", "Europe Stock"),
                  c("International Equity", "Latin America Stock"),
                  c("International Equity", "Pacific/Asia ex-Japan Stock"),
                  c("International Equity", "China Region"),
                  c("International Equity", "India Equity"),
                  c("International Equity", "Japan Stock"),
                  c("Alternative", "Bear Market"),
                  c("Alternative", "Multicurrency"),
                  c("Alternative", "Single Currency"),
                  c("Alternative", "Long-Short Credit"),
                  c("Alternative", "Long-Short Equity"),
                  c("Alternative", "Market Neutral"),
                  c("Alternative", "Multialternative"),
                  c("Alternative", "Managed Futures"),
                  c("Alternative", "Option Writing"),
                  c("Alternative", "Volatility"),
                  c("Alternative", "Trading--Leveraged Commodities"),
                  c("Alternative", "Trading--Inverse Commodities"),
                  c("Alternative", "Trading--Leveraged Debt"),
                  c("Alternative", "Trading--Inverse Debt"),
                  c("Alternative", "Trading--Leveraged Equity"),
                  c("Alternative", "Trading--Inverse Equity"),
                  c("Alternative", "Trading--Miscellaneous"),
                  c("Commodities", "Commodities Agriculture"),
                  c("Commodities", "Commodities Broad Basket"),
                  c("Commodities", "Commodities Energy"),
                  c("Commodities", "Commodities Industrial Metals"),
                  c("Commodities", "Commodities Miscellaneous"),
                  c("Commodities", "Commodities Precious Metals"),
                  c("Taxable Bond", "Long Government"),
                  c("Taxable Bond", "Intermediate Government"),
                  c("Taxable Bond", "Short Government"),
                  c("Taxable Bond", "Inflation-Protected Bond"),
                  c("Taxable Bond", "Long-Term Bond"),
                  c("Taxable Bond", "Intermediate-Term Bond"),
                  c("Taxable Bond", "Short-Term Bond"),
                  c("Taxable Bond", "Ultrashort Bond"),
                  c("Taxable Bond", "Bank Loan"),
                  c("Taxable Bond", "Stable Value"),
                  c("Taxable Bond", "Corporate Bond"),
                  c("Taxable Bond", "Preferred Stock"),
                  c("Taxable Bond", "High-Yield Bond"),
                  c("Taxable Bond", "Multisector Bond"),
                  c("Taxable Bond", "World Bond"),
                  c("Taxable Bond", "Emerging-Markets Bond"),
                  c("Taxable Bond", "Emerging-Markets Local-Currency Bond"),
                  c("Taxable Bond", "Nontraditional Bond"),
                  c("Municipal Bond", "Muni National Long"),
                  c("Municipal Bond", "Muni National Intermediate"),
                  c("Municipal Bond", "Muni National Short"),
                  c("Municipal Bond", "High-Yield Muni"),
                  c("Municipal Bond", "Muni Single State Long"),
                  c("Municipal Bond", "Muni Single State Intermediate"),
                  c("Municipal Bond", "Muni Single State Short"),
                  c("Municipal Bond", "Muni California Long"),
                  c("Municipal Bond", "Muni California Intermediate"),
                  c("Municipal Bond", "Muni Massachusetts"),
                  c("Municipal Bond", "Muni Minnesota"),
                  c("Municipal Bond", "Muni New Jersey"),
                  c("Municipal Bond", "Muni New York Long"),
                  c("Municipal Bond", "Muni New York Intermediate"),
                  c("Municipal Bond", "Muni Ohio"),
                  c("Municipal Bond", "Muni Pennsylvania"),
                  c("Money Market", "Taxable Money Market"),
                  c("Money Market", "Tax-Free Money Market"),
                  c("Money Market", "Prime Money Market")
                 )

colnames(Categories)<- c("CategoryGroup","Category")

formattable(Categories)
